name: PC Virtual Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        tar -xf ngrok.zip

    - name: Auth Ngrok
      run: |
        .\ngrok.exe config add-authtoken 39Gi0uYKr7y2GEWWwYXkCGxuxxP_3mkRKmwsFUKRgqN3QbKBh

    - name: Create User
      run: |
        net user joadonias Pc@2026Win! /add
        net localgroup administrators joadonias /add

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start RDP Tunnel
      run: |
        Start-Process .\ngrok.exe "tcp 3389"

    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 60 }
