name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip

    - name: Auth Ngrok
      run: |
        .\ngrok\ngrok.exe authtoken 39Gi0uYKr7y2GEWWwYXkCGxuxxP_3mkRKmwsFUKRgqN3QbKBh

    - name: Enable RDP
      run: |
        net user joadonias Pc@2026Win! /add
        net localgroup administrators joadonias /add
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start RDP Tunnel
      run: |
        .\ngrok\ngrok.exe tcp 3389
